
FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "ethernal_assignment.asgi:application", "--bind", "0.0.0.0:8000"]
