# Generated by Django 5.1 on 2024-08-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feedrate', models.FloatField()),
                ('max_acceleration', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('angular_units', models.FloatField()),
                ('velocity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('actual_position_x', models.FloatField()),
                ('actual_position_y', models.FloatField()),
                ('actual_position_z', models.FloatField()),
                ('actual_position_a', models.FloatField()),
                ('actual_position_c', models.FloatField()),
                ('distance_to_go_x', models.FloatField()),
                ('distance_to_go_y', models.FloatField()),
                ('distance_to_go_z', models.FloatField()),
                ('distance_to_go_a', models.FloatField()),
                ('distance_to_go_c', models.FloatField()),
                ('homed_x', models.BooleanField()),
                ('homed_y', models.BooleanField()),
                ('homed_z', models.BooleanField()),
                ('homed_a', models.BooleanField()),
                ('homed_c', models.BooleanField()),
                ('tool_offset_x', models.FloatField()),
                ('tool_offset_y', models.FloatField()),
                ('tool_offset_z', models.FloatField()),
                ('tool_offset_a', models.FloatField()),
                ('tool_offset_c', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_config.machineconfig')),
            ],
        ),
    ]
