# Generated by Django 5.1 on 2024-08-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('feedrate', models.FloatField()),
                ('max_acceleration', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('acceleration', models.FloatField()),
                ('angular_units', models.FloatField()),
                ('velocity', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='machinedata',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_config.machine'),
        ),
        migrations.AlterUniqueTogether(
            name='machinedata',
            unique_together={('machine', 'timestamp')},
        ),
        migrations.DeleteModel(
            name='MachineConfig',
        ),
    ]
